# coding: utf-8

"""
    RAG SIT x Stackit

    The perfect rag solution.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_backend.rag_backend_client.openapi_client.api.rag_api import RagApi


class TestRagApi(unittest.TestCase):
    """RagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RagApi()

    def tearDown(self) -> None:
        pass

    def test_chat(self) -> None:
        """Test case for chat"""
        pass

    def test_remove_source_documents(self) -> None:
        """Test case for remove_source_documents"""
        pass

    def test_search(self) -> None:
        """Test case for search"""
        pass

    def test_upload_source_documents(self) -> None:
        """Test case for upload_source_documents

        Upload Files for RAG.
        """
        pass


if __name__ == "__main__":
    unittest.main()
