# coding: utf-8

"""
    RAG SIT x Stackit

    The perfect rag solution.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_backend.rag_backend_client.openapi_client.models.upload_source_document import UploadSourceDocument


class TestUploadSourceDocument(unittest.TestCase):
    """UploadSourceDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadSourceDocument:
        """Test UploadSourceDocument
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UploadSourceDocument`
        """
        model = UploadSourceDocument()
        if include_optional:
            return UploadSourceDocument(
                content_type = 'TEXT',
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                content = ''
            )
        else:
            return UploadSourceDocument(
                content_type = 'TEXT',
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                content = '',
        )
        """

    def testUploadSourceDocument(self):
        """Test UploadSourceDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
