# coding: utf-8

"""
    RAG SIT x Stackit

    The perfect rag solution.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_backend.rag_backend_client.openapi_client.models.source_document import SourceDocument


class TestSourceDocument(unittest.TestCase):
    """SourceDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceDocument:
        """Test SourceDocument
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SourceDocument`
        """
        model = SourceDocument()
        if include_optional:
            return SourceDocument(
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                content = ''
            )
        else:
            return SourceDocument(
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                content = '',
        )
        """

    def testSourceDocument(self):
        """Test SourceDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
