replicaCount: 1
extractor:
  image:
    repository: schwarzit-xx-sit-rag-template-sit-stackit-docker-local.jfrog.io
    name: document-extractor
    pullPolicy: Always
    tag: "443892"

  command:
  - "poetry"
  - "run"
  args:
  - "python"
  - "-m"
  - "uvicorn"
  - "openapi_server.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"
  debugArgs:
  - "python"
  - "-m"
  - "debugpy"
  - "--wait-for-client"
  - "--listen"
  - "0.0.0.0:31415"
  - "-m"
  - "uvicorn"
  - "openapi_server.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"
  - "--reload"

admin_backend:
  image:
    repository: schwarzit-xx-sit-rag-template-sit-stackit-docker-local.jfrog.io
    name: admin-backend
    pullPolicy: Always
    tag: "443892"

  command:
  - "poetry"
  - "run"
  args:
  - "python"
  - "-m"
  - "uvicorn"
  - "admin_backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"
  - "--root-path"
  - "/api"
  debugArgs:
  - "python"
  - "-m"
  - "debugpy"
  - "--wait-for-client"
  - "--listen"
  - "0.0.0.0:31415"
  - "-m"
  - "uvicorn"
  - "admin_backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"
  - "--reload"
  - "--root-path"
  - "/api"

service:
  type: ClusterIP
  port: 8080

pythonPathEnv:
  PYTHONPATH: src

ingress:
  enabled: true
  host:
    name: admin.rag.localhost
    path: /api(/|$)(.*)
    pathType: ImplementationSpecific
    port: 8080

minio:
  enabled: true
