version: '3.8'
services:
  chat-app:
    build:
      context: ..
      dockerfile: frontend/apps/chat-app/Dockerfile
    ports:
      - "8080:8080"
  admin-app:
    build:
      context: ..
      dockerfile: frontend/apps/admin-app/Dockerfile
    ports:
      - "8081:8080"
