apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "configmap.logging.name" . }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret.name }}
      containers:
      - name: {{ .Chart.Name }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
        image: {{ include "fullimagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if not (empty .Values.command) }}
        command:
        {{- range $cmd :=  .Values.command }}
        - {{ $cmd -}}
        {{ end }}
        {{- end }}
        {{- if not .Values.global.debug.backend.enabled }}
        {{- if not (empty .Values.args) }}
        args:
        {{- range $arg :=  .Values.args }}
        - {{ $arg | quote -}}
        {{ end }}
        - "--workers"
        - {{ .Values.workers  | quote}}
        - "--ws-max-queue"
        - {{ .Values.ws_max_queue | quote }}
        {{- end }}
        {{- else }}
        {{- if not (empty .Values.debugArgs) }}
        args:
        {{- range $arg :=  .Values.debugArgs }}
        - {{ $arg | quote -}}
        {{ end }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.port }}
        {{- if .Values.global.debug.enabled }}
        - containerPort: 31415
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ template "configmap.errormessages.name" . }}
          - configMapRef:
              name: {{ template "configmap.database.name" . }}
          - configMapRef:
              name: {{ template "configmap.rag-class-types.name" . }}
          - configMapRef:
              name: {{ template "configmap.embedder-class-types.name" . }}
          - configMapRef:
              name: {{ template "configmap.retriever.name" . }}
          - configMapRef:
              name: {{ template "configmap.reranker.name" . }}
          - configMapRef:
              name: {{ template "configmap.alephalpha.name" . }}
          - configMapRef:
              name: {{ template "configmap.langfuse.name" . }}
          - configMapRef:
              name: {{ template "configmap.public.name" . }}
          - configMapRef:
              name: {{ template "configmap.ollama.name" . }}
          - configMapRef:
              name: {{ template "configmap.stackit-myapi-llm.name" . }}
          - configMapRef:
              name: {{ template "configmap.usecase.name" . }}
          - configMapRef:
              name: {{ template "configmap.ragas.name" . }}
          - configMapRef:
              name: {{ template "configmap.stackit-vllm.name" . }}
          - configMapRef:
              name: {{ template "configmap.stackit-embedder.name" . }}
          - secretRef:
              name: {{ template "secret.alephalpha.name" . }}
          - secretRef:
              name: {{ template "secret.langfuse.name" . }}
          - secretRef:
              name: {{ template "secret.openai.name" . }}
          - secretRef:
              name: {{ template "secret.stackit-myapi-llm.name" . }}
          - secretRef:
              name: {{ template "secret.stackit-vllm.name" . }}
          - secretRef:
              name: {{ template "secret.usecase.name" . }}
          - secretRef:
              name: {{ template "secret.stackit-vllm.name" . }}
          - secretRef:
              name: {{ template "secret.stackit-embedder.name" . }}
        env:
          - name: PYTHONPATH
            value: {{ .Values.pythonPathEnv.PYTHONPATH }}
