apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.database.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.database }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.retriever.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.retriever }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.alephalpha.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.aleph_alpha }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.langfuse.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.langfuse }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.errormessages.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.errormessages }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.rag-class-types.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.rag_class_types }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.reranker.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.reranker }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.embedder-class-types.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.embedder_class_types }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.stackit-myapi-llm.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.stackit_myapi_llm }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.public.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.public }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.ollama.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.ollama }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.usecase.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.usecase }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.ragas.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.ragas }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
