{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.backend.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.host.name }}, admin.{{ .Values.ingress.host.name }}"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    nginx.ingress.kubernetes.io/cors-max-age: "100"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- if .Values.global.config.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.global.config.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.global.config.tls.host }}
      secretName: {{ .Values.global.config.tls.secretName }}
  {{- end }}
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
        - path: {{ .Values.ingress.host.path }}
          pathType: {{ .Values.ingress.host.pathType }}
          backend:
            service:
              name: {{ $.Chart.Name }}
              port:
                number: {{ .Values.ingress.host.port }}
{{- end }}
