ragBase:
  langfuse:
    postgresql:
      deploy: true
      auth:
        username: postgres
        password: postgres
        database: langfuse
    langfuse:
      nextauth:
        url: http://localhost:3000
        secret: changeme
      salt: changeme
      additionalEnv:
        HOSTNAME: 0.0.0.0
        LANGFUSE_INIT_ORG_ID:
        LANGFUSE_INIT_PROJECT_ID:
        LANGFUSE_INIT_PROJECT_PUBLIC_KEY:
        LANGFUSE_INIT_PROJECT_SECRET_KEY:
        LANGFUSE_INIT_USER_EMAIL:
        LANGFUSE_INIT_USER_NAME:
        LANGFUSE_INIT_USER_PASSWORD:
