{{ if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configmap.name" . }}
data:
  {{- range $key, $value := .Values.global.config.envs.frontend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
