# coding: utf-8

"""
    RAG SIT x Stackit

    The perfect rag solution.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_api_lib.rag_backend_client.openapi_client.api.rag_api import RagApi


class TestRagApi(unittest.TestCase):
    """RagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RagApi()

    def tearDown(self) -> None:
        pass

    def test_chat(self) -> None:
        """Test case for chat"""
        pass

    def test_evaluate(self) -> None:
        """Test case for evaluate"""
        pass

    def test_remove_information_piece(self) -> None:
        """Test case for remove_information_piece

        remove information piece
        """
        pass

    def test_upload_information_piece(self) -> None:
        """Test case for upload_information_piece

        Upload information pieces for vectordatabase
        """
        pass


if __name__ == "__main__":
    unittest.main()
