{{ if .Values.global.imagePullSecret.create }}
apiVersion: v1
data:
    .dockerconfigjson: {{ include "rag.dockerconfigjson" . }}
kind: Secret
metadata:
    name: {{ .Values.global.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}
