{{- if and .Values.features.langfuse.enabled .Values.langfuseRetention.enabled }}
{{- $retentionImage := printf "%s:%s" .Values.langfuseRetention.image.repository .Values.langfuseRetention.image.tag -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-langfuse-retention" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: rag
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.langfuseRetention.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: rag
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: apply-clickhouse-ttl
              image: {{ $retentionImage | quote }}
              imagePullPolicy: {{ .Values.langfuseRetention.image.pullPolicy | quote }}
              command:
                - /bin/bash
                - -ec
              args:
                - |
                  set -euo pipefail

                  PASSWORD="${CLICKHOUSE_PASSWORD:-}"
                  if [ -z "${PASSWORD}" ]; then
                    PASSWORD="${CLICKHOUSE_PASSWORD_LITERAL:-}"
                  fi

                  if [ -z "${PASSWORD}" ]; then
                    echo "No ClickHouse password found. Check langfuse.clickhouse.auth settings and secret."
                    exit 1
                  fi

                  ON_CLUSTER_CLAUSE=""
                  if [ "${CLICKHOUSE_ON_CLUSTER}" = "true" ]; then
                    ON_CLUSTER_CLAUSE=" ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME}"
                  fi

                  TABLE_ROWS="$(cat <<'EOF_TABLES'
                  {{- range .Values.langfuseRetention.clickhouse.tables }}
                  {{ .name }}	{{ .timestampColumn }}
                  {{- end }}
                  EOF_TABLES
                  )"

                  while IFS=$'\t' read -r table ts_col; do
                    [ -z "${table}" ] && continue

                    echo "Applying TTL=${RETENTION_DAYS}d to ${CLICKHOUSE_DATABASE}.${table} (${ts_col})"
                    clickhouse-client \
                      --host "${CLICKHOUSE_HOST}" \
                      --port "${CLICKHOUSE_PORT}" \
                      --user "${CLICKHOUSE_USER}" \
                      --password "${PASSWORD}" \
                      --query "ALTER TABLE ${CLICKHOUSE_DATABASE}.${table}${ON_CLUSTER_CLAUSE} MODIFY TTL toDateTime(${ts_col}) + toIntervalDay(${RETENTION_DAYS})"
                  done <<< "${TABLE_ROWS}"
              env:
{{ include "rag.langfuseRetentionClickhouseEnv" . | nindent 16 }}
{{- end }}
