{{ if .Values.shared.imagePullSecret }}
{{ if .Values.shared.imagePullSecret.create }}
apiVersion: v1
data:
    .dockerconfigjson: {{ include "rag.dockerconfigjson" . }}
kind: Secret
metadata:
    name: {{ .Values.shared.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
