{{- $s3 := .Values.shared.secrets.s3 }}
{{- $s3Access := fromYaml (include "rag.secretConfig" $s3.accessKey) }}
{{- $s3Secret := fromYaml (include "rag.secretConfig" $s3.secretKey) }}
{{- $s3AccessExternal := include "rag.secretIsExternal" (dict "config" $s3Access) | fromYaml | default false }}
{{- $s3SecretExternal := include "rag.secretIsExternal" (dict "config" $s3Secret) | fromYaml | default false }}
{{- if not (and $s3AccessExternal $s3SecretExternal) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.s3Name" . }}
type: Opaque
data:
  {{- if not $s3AccessExternal }}
  {{ include "rag.secretRefKey" (dict "config" $s3Access "defaultKey" "S3_ACCESS_KEY_ID") }}: {{ default "" $s3Access.value | b64enc }}
  {{- end }}
  {{- if not $s3SecretExternal }}
  {{ include "rag.secretRefKey" (dict "config" $s3Secret "defaultKey" "S3_SECRET_ACCESS_KEY") }}: {{ default "" $s3Secret.value | b64enc }}
  {{- end }}
{{- end }}
{{- $usecaseSecretData := dict }}
{{- range $key, $cfg := .Values.shared.secrets.usecase }}
  {{- $entry := fromYaml (include "rag.secretConfig" $cfg) }}
  {{- $usecaseExternal := include "rag.secretIsExternal" (dict "config" $entry) | fromYaml | default false }}
  {{- if not $usecaseExternal }}
    {{- $secretKey := include "rag.secretRefKey" (dict "config" $entry "defaultKey" $key) }}
    {{- $_ := set $usecaseSecretData $secretKey (default "" $entry.value | b64enc) }}
  {{- end }}
{{- end }}
{{- if gt (len $usecaseSecretData) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.usecaseName" . }}
type: Opaque
data:
{{- range $key, $val := $usecaseSecretData }}
  {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
