# coding: utf-8

"""
STACKIT RAG

The perfect rag solution.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from rag_backend_client.openapi_client.models.chat_role import ChatRole


class TestChatRole(unittest.TestCase):
    """ChatRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatRole(self):
        """Test ChatRole"""
        # inst = ChatRole()


if __name__ == "__main__":
    unittest.main()
