openapi: 3.0.2
info:
  title: rag_document_extractor
  version: 1.0.0
servers:
- url: /
paths:
  /extract:
    post:
      operationId: extract_information
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InformationPiece'
                type: array
          description: List of extracted information.
        "422":
          description: Body is not a valid PDF.
        "500":
          description: Something somewhere went terribly wrong.
      tags:
      - extractor
components:
  schemas:
    InformationPiece:
      description: A piece of information that has been extracted.
      example:
        Type: null
        Content: Content
        MetaInformation:
        - Value: ""
          Key: ""
        - Value: ""
          Key: ""
      properties:
        Content:
          description: ""
          title: Content
          type: string
        Type:
          $ref: '#/components/schemas/InformationType'
        MetaInformation:
          description: ""
          items:
            $ref: '#/components/schemas/MetaInformationPiece'
          title: MetaInformation
          type: array
      required:
      - Content
      - MetaInformation
      - Type
      title: InformationPiece
      type: object
    InformationType:
      description: ""
      enum:
      - IMAGE
      - TABLE
      - TEXT
      title: InformationType
      type: string
    MetaInformationPiece:
      description: ""
      example:
        Value: ""
        Key: ""
      properties:
        Key:
          description: ""
          title: Key
        Value:
          description: ""
          title: Value
      title: MetaInformationPiece
      type: object
    ExtractionRequest:
      description: ""
      example:
        PathOnS3: PathOnS3
      properties:
        PathOnS3:
          description: ""
          title: PathOnS3
          type: string
      required:
      - PathOnS3
      title: ExtractionRequest
      type: object
