{{- $kvCreds := (include "keyValueStore.credentials" . | fromYaml) -}}
{{- if or $kvCreds.username $kvCreds.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.keyValueStoreName" . }}
type: Opaque
data:
  {{- if $kvCreds.username }}
  USECASE_KEYVALUE_USERNAME: {{ $kvCreds.username | b64enc }}
  {{- end }}
  {{- if $kvCreds.password }}
  USECASE_KEYVALUE_PASSWORD: {{ $kvCreds.password | b64enc }}
  {{- end }}
{{- end }}
