apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.keyvalName" . }}
type: Opaque
data:
  USECASE_KEYVALUE_USERNAME: {{ .Values.adminBackend.secrets.keyvalue.username | b64enc }}
  USECASE_KEYVALUE_PASSWORD: {{ .Values.adminBackend.secrets.keyvalue.password | b64enc }}
