apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminBackend.name }}
spec:
  type: {{ .Values.adminBackend.service.type }}
  ports:
  - port: {{ .Values.adminBackend.service.port }}
    targetPort: {{ .Values.adminBackend.service.port }}
  selector:
    app: {{ .Values.adminBackend.name }}
