apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.extractor.name }}
spec:
  replicas: {{ .Values.extractor.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.extractor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.extractor.name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "configmap.loggingName" . }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret.name }}
      containers:
      - name: {{ .Values.extractor.name }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
        image: {{ template "extractor.fullImageName" . }}
        imagePullPolicy: {{ .Values.extractor.image.pullPolicy }}
        {{- if not (empty .Values.extractor.command) }}
        command:
        {{- range $cmd :=  .Values.extractor.command }}
        - {{ $cmd -}}
        {{ end }}
        {{- end }}
        {{- if not .Values.global.debug.backend.enabled }}
        {{- if not (empty .Values.extractor.args) }}
        args:
        {{- range $arg :=  .Values.extractor.args }}
        - {{ $arg | quote -}}
        {{ end }}
        {{- end }}
        {{- else }}
        {{- if not (empty .Values.extractor.debugArgs) }}
        args:
        {{- range $arg :=  .Values.extractor.debugArgs }}
        - {{ $arg | quote -}}
        {{ end }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.extractor.service.port }}
        {{- if .Values.global.debug.backend.enabled }}
        - containerPort: 31415
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ template "configmap.s3Name" . }}
          - configMapRef:
              name: {{ template "configmap.pdfextractorName" . }}
          - secretRef:
              name: {{ template "secret.s3Name" . }}
        env:
          - name: PYTHONPATH
            value: {{ .Values.extractor.pythonPathEnv.PYTHONPATH }}
