apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: rag
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
