# coding: utf-8

"""
    RAG SIT x Stackit

    The perfect rag solution.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from rag_core.apis.rag_api import router as RagApiRouter
from rag_core.container import Container

app = FastAPI(
    title="RAG SIT x Stackit",
    description="The perfect rag solution.",
    version="1.0.0",
)

app.include_router(RagApiRouter)

container = Container()
app.container = container


def register_dependency(name, instance):
    # TODO: this can currently only replace. Implement adding new dependencies!
    dependency = getattr(app.container, name)
    dependency.override(instance)
