{{- if and .Values.features.externalSecrets.enabled .Values.externalSecrets.resources.enabled }}
{{- $store := .Values.externalSecrets.secretStore }}
{{- $storeKind := default "SecretStore" $store.kind }}
{{- $storeName := default "stackit-vault" $store.name }}
{{- $remoteKey := default "rag-secrets" .Values.externalSecrets.remoteRefKey }}
{{- $refreshInterval := default "1h" .Values.externalSecrets.refreshInterval }}
{{- $userPassSecretRef := $store.auth.userPass.secretRef }}
{{- $clusterSecretNamespace := default .Release.Namespace $userPassSecretRef.namespace }}
{{- if $store.create }}
apiVersion: external-secrets.io/v1
kind: {{ $storeKind }}
metadata:
  name: {{ $storeName }}
  {{- if ne $storeKind "ClusterSecretStore" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  provider:
    vault:
      server: {{ $store.server | quote }}
      path: {{ $store.path | quote }}
      version: {{ $store.version | quote }}
      auth:
        userPass:
          path: {{ $store.auth.userPass.path | quote }}
          username: {{ $store.auth.userPass.username | quote }}
          secretRef:
            name: {{ $store.auth.userPass.secretRef.name | quote }}
            key: {{ $store.auth.userPass.secretRef.key | quote }}
            {{- if eq $storeKind "ClusterSecretStore" }}
            namespace: {{ $clusterSecretNamespace | quote }}
            {{- end }}
---
{{- end }}
{{- if and .Values.externalSecrets.userPassSecret.create .Values.externalSecrets.userPassSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalSecrets.userPassSecret.name | quote }}
  namespace: {{ default .Release.Namespace .Values.externalSecrets.userPassSecret.namespace | quote }}
type: Opaque
stringData:
  password: {{ .Values.externalSecrets.userPassSecret.password | quote }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: rag-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_PUBLIC_KEY
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_SECRET_KEY
    - secretKey: STACKIT_EMBEDDER_API_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: STACKIT_EMBEDDER_API_KEY
    - secretKey: STACKIT_VLLM_API_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: STACKIT_VLLM_API_KEY
    - secretKey: RAGAS_OPENAI_API_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: RAGAS_OPENAI_API_KEY
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: {{ $remoteKey }}
        property: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: S3_SECRET_ACCESS_KEY
    - secretKey: LANGFUSE_SALT
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_SALT
    - secretKey: LANGFUSE_NEXTAUTH
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_NEXTAUTH
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vite-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: vite-auth
    creationPolicy: Owner
  data:
    - secretKey: VITE_AUTH_USERNAME
      remoteRef:
        key: {{ $remoteKey }}
        property: BASIC_AUTH_USER
    - secretKey: VITE_AUTH_PASSWORD
      remoteRef:
        key: {{ $remoteKey }}
        property: BASIC_AUTH_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: basic-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: {{ $remoteKey }}
        property: BASIC_AUTH
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-init-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: langfuse-init-secrets
    creationPolicy: Owner
  data:
    - secretKey: LANGFUSE_INIT_ORG_ID
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_INIT_ORG_ID
    - secretKey: LANGFUSE_INIT_PROJECT_ID
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_INIT_PROJECT_ID
    - secretKey: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_PUBLIC_KEY
    - secretKey: LANGFUSE_INIT_PROJECT_SECRET_KEY
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_SECRET_KEY
    - secretKey: LANGFUSE_INIT_USER_EMAIL
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_INIT_USER_EMAIL
    - secretKey: LANGFUSE_INIT_USER_NAME
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_INIT_USER_NAME
    - secretKey: LANGFUSE_INIT_USER_PASSWORD
      remoteRef:
        key: {{ $remoteKey }}
        property: LANGFUSE_INIT_USER_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-postgres
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: rag-postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ $remoteKey }}
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-redis
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: rag-redis
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ $remoteKey }}
        property: REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: rag-clickhouse
    creationPolicy: Owner
  data:
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: {{ $remoteKey }}
        property: CLICKHOUSE_PASSWORD
{{- end }}
