# coding: utf-8

"""
    rag_pdf_extractor

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.extractor_api import router as ExtractorApiRouter
from openapi_server.container import Container

app = FastAPI(
    title="rag_pdf_extractor",
    description="Service for extracting the content (e.g. text, images and tables) from a pdf.",
    version="1.0.0",
)

container = Container()
app.container = container
app.include_router(ExtractorApiRouter)
