apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certIssuer.name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.certIssuer.server | quote }}
    # Email address used for ACME registration
    email: {{ .Values.certIssuer.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.certIssuer.privateKeySecretName }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certIssuer.ingressClass | quote }}
