# coding: utf-8

"""
    rag_document_extractor

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_backend.document_extractor_client.openapi_client.models.meta_information_piece import (
    MetaInformationPiece,
)


class TestMetaInformationPiece(unittest.TestCase):
    """MetaInformationPiece unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetaInformationPiece:
        """Test MetaInformationPiece
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MetaInformationPiece`
        """
        model = MetaInformationPiece()
        if include_optional:
            return MetaInformationPiece(
                key = None,
                value = None
            )
        else:
            return MetaInformationPiece(
        )
        """

    def testMetaInformationPiece(self):
        """Test MetaInformationPiece"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
