# coding: utf-8

"""
    rag_document_extractor

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_backend.document_extractor_client.openapi_client.models.information_type import (
    InformationType,
)


class TestInformationType(unittest.TestCase):
    """InformationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInformationType(self):
        """Test InformationType"""
        # inst = InformationType()


if __name__ == "__main__":
    unittest.main()
