{{- if $.Values.features.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminFrontend.name }}
spec:
  type: {{ .Values.adminFrontend.service.type }}
  ports:
    - port: {{ .Values.adminFrontend.service.port }}
      targetPort: {{ .Values.adminFrontend.service.port }}
  selector:
    app: {{ .Values.adminFrontend.name }}
{{- end }}
