{{- if $.Values.features.frontend.enabled }}
apiVersion: v1
data:
  VITE_AUTH_USERNAME: {{ .Values.shared.secrets.basicAuthUser.value | b64enc }}
  VITE_AUTH_PASSWORD: {{ .Values.shared.secrets.basicAuthPassword.value | b64enc }}
kind: Secret
metadata:
  name: vite-auth
type: Opaque
{{- end }}
