{{- if $.Values.features.frontend.enabled }}
{{- $viteAuthData := dict }}
{{- $meta := dict "allExternal" true }}
{{- range $key, $cfg := .Values.frontend.secrets.viteAuth }}
  {{- $entry := fromYaml (include "rag.secretConfig" $cfg) }}
  {{- $viteAuthExternal := include "rag.secretIsExternal" (dict "config" $entry) | fromYaml | default false }}
  {{- if not $viteAuthExternal }}
    {{- $_ := set $meta "allExternal" false }}
    {{- $secretKey := include "rag.secretRefKey" (dict "config" $entry "defaultKey" $key) }}
    {{- $_ := set $viteAuthData $secretKey (default "" $entry.value | b64enc) }}
  {{- end }}
{{- end }}
{{- if eq (len .Values.frontend.secrets.viteAuth) 0 }}
  {{- $_ := set $meta "allExternal" false }}
{{- end }}
{{- if not $meta.allExternal }}
apiVersion: v1
data:
{{- range $key, $val := $viteAuthData }}
  {{ $key }}: {{ $val }}
{{- end }}
kind: Secret
metadata:
  name: vite-auth
type: Opaque
{{- end }}
{{- end }}
