{{- if $.Values.features.frontend.enabled }}
apiVersion: v1
data:
  {{- range $key, $value := .Values.frontend.secrets.viteAuth }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: vite-auth
type: Opaque
{{- end }}
