{{- $basicAuth := (include "rag.basicAuthCredentials" . | fromYaml) }}
{{- if and $.Values.features.frontend.enabled $basicAuth.username $basicAuth.password }}
apiVersion: v1
data:
  VITE_AUTH_USERNAME: {{ $basicAuth.username | b64enc }}
  VITE_AUTH_PASSWORD: {{ $basicAuth.password | b64enc }}
kind: Secret
metadata:
  name: vite-auth
type: Opaque
{{- end }}
