# coding: utf-8

"""
    extractor-api-lib

    Extractor API lib

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import logging.config
import yaml

from fastapi import FastAPI

from extractor_api_lib.apis.extractor_api import router
from extractor_api_lib.container import Container


with open("/config/logging.yaml", "r") as stream:
    config = yaml.safe_load(stream)
logging.config.dictConfig(config)

app = FastAPI(
    title="extractor-api-lib",
    description="Extractor API lib",
    version="1.0.0",
)

app.include_router(router)

container = Container()
app.container = container


def register_dependency_container(new_container: Container):
    # preserve old wiring
    wiring_target = container.wiring_config.modules
    app.container.override(new_container)

    # rewire
    wiring_target = list(set(wiring_target + new_container.wiring_config.modules))
    app.container.wire(modules=wiring_target)
