FROM python:3.11.7-bookworm

WORKDIR /app

ARG standalone=1

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential --no-install-recommends make libhdf5-dev

RUN pip install poetry==1.8.3

