apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}      
    spec:
      volumes:
      - name: adminfrontend
        emptyDir: {}
      initContainers:
      - name: admin-frontend-copy
        image: {{ template "fullimagename" . }}
        envFrom:
          - configMapRef:
              name: {{ template "configmap.name" . }}
          - secretRef:
              name: "vite-auth"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: adminfrontend        
        command: ["cp","-r", "/app/frontend/.", "/usr/share/nginx/html"]
      - name: vite-workaround
        command: 
          - /bin/sh
        args: 
          - /app/env.sh
        image: {{ template "fullimagename" . }}
        envFrom:
          - configMapRef:
              name: {{ template "configmap.name" . }}
          - secretRef:
              name: "vite-auth"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: adminfrontend        
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "fullimagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: adminfrontend
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
          - configMapRef:
              name: {{ template "configmap.name" . }}
          - secretRef:
              name: "vite-auth"
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret.name }}
