# coding: utf-8

"""
extractor-api-lib

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_api_lib.extractor_api_client.openapi_client.models.content_type import ContentType


class TestContentType(unittest.TestCase):
    """ContentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentType(self):
        """Test ContentType"""
        # inst = ContentType()


if __name__ == "__main__":
    unittest.main()
