# coding: utf-8

"""
extractor-api-lib

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_api_lib.extractor_api_client.openapi_client.models.information_piece import InformationPiece


class TestInformationPiece(unittest.TestCase):
    """InformationPiece unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InformationPiece:
        """Test InformationPiece
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InformationPiece`
        """
        model = InformationPiece()
        if include_optional:
            return InformationPiece(
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                page_content = '',
                type = 'IMAGE'
            )
        else:
            return InformationPiece(
                metadata = [
                    {"value":"value","key":"key"}
                    ],
                page_content = '',
                type = 'IMAGE',
        )
        """

    def testInformationPiece(self):
        """Test InformationPiece"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
