# coding: utf-8

"""
extractor-api-lib

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from admin_api_lib.extractor_api_client.openapi_client.api.extractor_api import ExtractorApi


class TestExtractorApi(unittest.TestCase):
    """ExtractorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExtractorApi()

    def tearDown(self) -> None:
        pass

    def test_extract_from_file_post(self) -> None:
        """Test case for extract_from_file_post"""
        pass

    def test_extract_from_source(self) -> None:
        """Test case for extract_from_source"""
        pass


if __name__ == "__main__":
    unittest.main()
