rag-base:
  langfuse:
    image:
      repository: ghcr.io/langfuse/langfuse
      pullPolicy: Always
      tag: "2.75.2"
    postgresql:
      deploy: true
      auth:
        username: postgres
        password: postgres
        database: langfuse
    langfuse:
      additionalEnv:
        HOSTNAME: 0.0.0.0
