{{- if $.Values.shared.ssl }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rag-certificate
spec:
  dnsNames:
    {{- range .Values.shared.config.dns }}
    - {{.}}
    {{- end }}
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
{{- end }}
