{{- $basicAuthData := include "rag.basicAuthSecretData" . }}
{{- if $basicAuthData }}
apiVersion: v1
data:
{{ $basicAuthData | nindent 2 }}
kind: Secret
metadata:
  name: {{ template "secret.basicAuthName" . }}
type: Opaque
{{- end }}
---
{{- if and .Values.backend.secrets.langfuse.publicKey.value .Values.backend.secrets.langfuse.secretKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.langfuseName" . }}
type: Opaque
data:
  LANGFUSE_PUBLIC_KEY: {{ .Values.backend.secrets.langfuse.publicKey.value | b64enc }}
  LANGFUSE_SECRET_KEY: {{ .Values.backend.secrets.langfuse.secretKey.value | b64enc }}
{{- end }}
---
{{- if .Values.backend.secrets.stackitVllm.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitVllmName" . }}
type: Opaque
data:
  STACKIT_VLLM_API_KEY: {{ .Values.backend.secrets.stackitVllm.apiKey.value | b64enc }}
{{- end }}
---
{{- if .Values.backend.secrets.stackitEmbedder.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitEmbedderName" . }}
type: Opaque
data:
  STACKIT_EMBEDDER_API_KEY: {{ .Values.backend.secrets.stackitEmbedder.apiKey.value | b64enc }}
{{- end }}
---
{{- if .Values.backend.secrets.ragas.openaiApikey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.ragasName" . }}
type: Opaque
data:
  RAGAS_OPENAI_API_KEY: {{ .Values.backend.secrets.ragas.openaiApikey.value | b64enc }}
{{- end }}
