{{- $basicAuth := fromYaml (include "rag.secretConfig" .Values.backend.secrets.basicAuth) }}
{{- $basicAuthExternal := include "rag.secretIsExternal" (dict "config" $basicAuth) | fromYaml | default false }}
{{- if not $basicAuthExternal }}
apiVersion: v1
data:
  {{ include "rag.secretRefKey" (dict "config" $basicAuth "defaultKey" "auth") }}: {{ default "" $basicAuth.value | b64enc }}
  {{- range $key, $value := .Values.backend.secrets.auth }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "secret.basicAuthName" . }}
type: Opaque
{{- end }}
{{- $langfusePublicKey := fromYaml (include "rag.secretConfig" .Values.backend.secrets.langfuse.publicKey) }}
{{- $langfuseSecretKey := fromYaml (include "rag.secretConfig" .Values.backend.secrets.langfuse.secretKey) }}
{{- $langfusePublicExternal := include "rag.secretIsExternal" (dict "config" $langfusePublicKey) | fromYaml | default false }}
{{- $langfuseSecretExternal := include "rag.secretIsExternal" (dict "config" $langfuseSecretKey) | fromYaml | default false }}
{{- if not (and $langfusePublicExternal $langfuseSecretExternal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.langfuseName" . }}
type: Opaque
data:
  {{- if not $langfusePublicExternal }}
  {{ include "rag.secretRefKey" (dict "config" $langfusePublicKey "defaultKey" "LANGFUSE_PUBLIC_KEY") }}: {{ default "" $langfusePublicKey.value | b64enc }}
  {{- end }}
  {{- if not $langfuseSecretExternal }}
  {{ include "rag.secretRefKey" (dict "config" $langfuseSecretKey "defaultKey" "LANGFUSE_SECRET_KEY") }}: {{ default "" $langfuseSecretKey.value | b64enc }}
  {{- end }}
{{- end }}
{{- $stackitVllm := fromYaml (include "rag.secretConfig" .Values.backend.secrets.stackitVllm.apiKey) }}
{{- $stackitVllmExternal := include "rag.secretIsExternal" (dict "config" $stackitVllm) | fromYaml | default false }}
{{- if not $stackitVllmExternal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitVllmName" . }}
type: Opaque
data:
  {{ include "rag.secretRefKey" (dict "config" $stackitVllm "defaultKey" "STACKIT_VLLM_API_KEY") }}: {{ default "" $stackitVllm.value | b64enc }}
{{- end }}
{{- $stackitEmbedder := fromYaml (include "rag.secretConfig" .Values.backend.secrets.stackitEmbedder.apiKey) }}
{{- $stackitEmbedderExternal := include "rag.secretIsExternal" (dict "config" $stackitEmbedder) | fromYaml | default false }}
{{- if not $stackitEmbedderExternal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitEmbedderName" . }}
type: Opaque
data:
  {{ include "rag.secretRefKey" (dict "config" $stackitEmbedder "defaultKey" "STACKIT_EMBEDDER_API_KEY") }}: {{ default "" $stackitEmbedder.value | b64enc }}
{{- end }}
{{- $ragas := fromYaml (include "rag.secretConfig" .Values.backend.secrets.ragas.openaiApikey) }}
{{- $ragasExternal := include "rag.secretIsExternal" (dict "config" $ragas) | fromYaml | default false }}
{{- if not $ragasExternal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.ragasName" . }}
type: Opaque
data:
  {{ include "rag.secretRefKey" (dict "config" $ragas "defaultKey" "RAGAS_OPENAI_API_KEY") }}: {{ default "" $ragas.value | b64enc }}
{{- end }}
