# coding: utf-8

# flake8: noqa
"""
extractor-api-lib

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from admin_api_lib.extractor_api_client.openapi_client.models.content_type import ContentType
from admin_api_lib.extractor_api_client.openapi_client.models.extraction_parameters import ExtractionParameters
from admin_api_lib.extractor_api_client.openapi_client.models.extraction_request import ExtractionRequest
from admin_api_lib.extractor_api_client.openapi_client.models.information_piece import InformationPiece
from admin_api_lib.extractor_api_client.openapi_client.models.key_value_pair import KeyValuePair
